# This file contains values from Cookiecutter

default_context:
  project_name: "denser-retriever"
  project_description: "Enterprise-grade AI retriever solution that seamlessly integrates to enhance your AI applications."
  organization: "denser-org"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "denser-org"
  email: "support@denser.ai"
  version: "0.1.0"
  line_length: "120"
  create_example_template: "cli"
